### ISSUE TITLE
request for help to build helpdesk successfully 

### ISSUE THREAD

**Issue by BabarShaikh786** [WarrenGarabrandt/Helpdesk#1]
Error	

NETSDK1045	The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.

**Comment by WarrenGarabrandt** [comment]
Keep in mind the project is still early stages, so you can play with it if you want, but it's definitely NOT ready for regular use right now. If you clone the repo, you should be able to build and run it. I'm researching some stuff I need to know in java script for the tickets and asset pages before development can continue. The pages I want to make are difficult to do without using java script, so that's holding the project up right now.

I recommend using Visual Studio 2022, and you'll need necessary components selected for build to complete. In the Visual Studio installer, make sure ASP.NET and web development are checked, as well as .NET desktop development. Under individual components, you need a few thing checked. I THINK this is all you need...but there are likely some that are default installed that I just never touched.
.NET 6.0 Runtime (LTS)
.NET Native
.NET SDK
Advanced ASP.NET Features
CLR Data types for SQL server
SQL Server express local db
Git for windows
NuGet package manager
NuGet targets and build tasks
C# and visual basic roslyn compilers.
MSBuild
ASP.NET and web development prerequisities
C# and Visual Basic
JavaScript and TypeScript language support
Razor Language Services
Entity Framework 6 Tools
Open JDK

**Comment by WarrenGarabrandt** [comment]
There was a model in the latest push that didn't have a primary key on it. This was a placeholder for a database table I was going to create for Tickets. I've resolved this with a few placeholders for now. The code will build and run now.
